#!/usr/bin/env python3

import argparse
import os
import subprocess
import sys

import hkml_init
import hkml_fetch
import hkml_format_reply
import hkml_ls
import hkml_send
import hkml_write
import manifest

import _hkml

class SubCmdHelpFormatter(argparse.RawDescriptionHelpFormatter):
    def _format_action(self, action):
        parts = super(argparse.RawDescriptionHelpFormatter,
                self)._format_action(action)
        # Skips subparsers help
        if action.nargs == argparse.PARSER:
            parts = '\n'.join(parts.split('\n')[1:])
        return parts

parser = argparse.ArgumentParser(formatter_class=SubCmdHelpFormatter)
parser.add_argument('--hkml_dir', metavar='hkml dir', type=str,
        help='Path to the hkml meta data directory.')

subparsers = parser.add_subparsers(title='command', dest='command',
        metavar='<command>')

parser_init = subparsers.add_parser('init', help = 'initialize working dir')
hkml_init.set_argparser(parser_init)

parser_fetch = subparsers.add_parser('fetch', help = 'fetch mails')
hkml_fetch.set_argparser(parser_fetch)

parser_ls = subparsers.add_parser('ls', help = 'list mails')
hkml_ls.set_argparser(parser_ls)

parser_fmtml = subparsers.add_parser('write', help = 'write a mail')
hkml_write.set_argparser(parser_fmtml)

parser_fmtre = subparsers.add_parser('format_reply', help = 'format reply')
hkml_format_reply.set_argparser(parser_fmtre)

parser_send = subparsers.add_parser('send', help = 'send mails')
hkml_send.set_argparser(parser_send)

parser_manifest = subparsers.add_parser('manifest', help = 'print manifest')
manifest.set_argparser(parser_manifest)

args = parser.parse_args()

if args.command in ['fetch', 'ls']:
    _hkml.set_hkml_dir(args.hkml_dir)

if not args.command:
    parser.print_help()
    exit(1)

if args.command == 'init':
    hkml_init.main(args)
elif args.command == 'ls':
    hkml_ls.main(args)
elif args.command == 'fetch':
    hkml_fetch.main(args)
elif args.command == 'write':
    hkml_write.main(args)
elif args.command == 'format_reply':
    hkml_format_reply.main(args)
elif args.command == 'send':
    hkml_send.main(args)
elif args.command == 'manifest':
    manifest.main(args)
else:
    print('wrong command (%s)' % args.command)
    exit(1)
