#!/usr/bin/env python3

import argparse
import os
import subprocess
import sys

import fetchmails
import format_mail
import format_reply
import lsmails
import manifest
import send

import _hkml

class SubCmdHelpFormatter(argparse.RawDescriptionHelpFormatter):
    def _format_action(self, action):
        parts = super(argparse.RawDescriptionHelpFormatter,
                self)._format_action(action)
        # Skips subparsers help
        if action.nargs == argparse.PARSER:
            parts = '\n'.join(parts.split('\n')[1:])
        return parts

parser = argparse.ArgumentParser(formatter_class=SubCmdHelpFormatter)
parser.add_argument('--hkml_dir', metavar='hkml dir', type=str,
        help='Path to the hkml meta data directory.')

subparsers = parser.add_subparsers(title='command', dest='command',
        metavar='<command>')

parser_init = subparsers.add_parser('init', help = 'initialize working dir')

parser_ls = subparsers.add_parser('ls', help = 'list mails')
lsmails.set_argparser(parser_ls)

parser_fetch = subparsers.add_parser('fetch', help = 'fetch mails')
fetchmails.set_argparser(parser_fetch)

parser_fmtml = subparsers.add_parser('format_mail', help = 'format a mail')
format_mail.set_argparser(parser_fmtml)

parser_fmtre = subparsers.add_parser('format_reply', help = 'format reply')
format_reply.set_argparser(parser_fmtre)

parser_send = subparsers.add_parser('send', help = 'send mails')
send.set_argparser(parser_send)

parser_manifest = subparsers.add_parser('manifest', help = 'print manifest')
manifest.set_argparser(parser_manifest)

args = parser.parse_args()

if args.command in ['fetch', 'ls']:
    _hkml.set_hkml_dir(args.hkml_dir)

if not args.command:
    parser.print_help()
    exit(1)

if args.command == 'init':
    os.mkdir('.hkm')
    os.mkdir('.hkm/archives')
elif args.command == 'ls':
    lsmails.main(args)
elif args.command == 'fetch':
    fetchmails.main(args)
elif args.command == 'format_mail':
    format_mail.main(args)
elif args.command == 'format_reply':
    format_reply.main(args)
elif args.command == 'send':
    send.main(args)
elif args.command == 'manifest':
    manifest.main(args)
